// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "ironchip.net/kit/users/pkg/endpoint"
	pb "ironchip.net/kit/users/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	list   grpc.Handler
	get    grpc.Handler
	create grpc.Handler
	delete grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.UsersServer {
	return &grpcServer{
		create: makeCreateHandler(endpoints, options["Create"]),
		delete: makeDeleteHandler(endpoints, options["Delete"]),
		get:    makeGetHandler(endpoints, options["Get"]),
		list:   makeListHandler(endpoints, options["List"]),
	}
}
